wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.19.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737041998
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 105
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 105
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.12.4
      5: 0.19.3
      8:
      - 5
      13: linux-x86_64
batch-size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.001
