_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 105
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.3
            "8":
                - 3
                - 5
            "12": 0.19.3
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
