name: "Run tests"

on:
  push:
    branches:
      - main 
      - lise
      - justine 
      - ruikangzhao
      - devWen
  pull_request:
    branches:
      - main 
      - lise
      - justine 
      - ruikangzhao
      - devWen

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install test dependencies
        run: pip install -r requirements_tests.txt

      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -m
